version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: beebleet-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: beebleet
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
